name: ci

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    test:
        runs-on: ${{ matrix.os }}
        timeout-minutes: 30
        strategy:
            fail-fast: false
            matrix:
                deno:
                    - v2.x
                os:
                    - ubuntu-22.04
                    - windows-2022

        steps:
            - name: Clone repository
              uses: actions/checkout@v4
              with:
                  submodules: true

            - name: Set up Deno
              uses: denoland/setup-deno@v2
              with:
                  deno-version: ${{ matrix.deno }}

            - name: Run tests
              run: deno task test

            - name: Generate lcov
              run: deno task cov:gen

            - name: Upload coverage
              uses: codecov/codecov-action@v4
              env:
                  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
              with:
                  name: ${{ matrix.os }}-${{ matrix.deno }}
                  files: cov.lcov

    lint:
        runs-on: ubuntu-22.04
        steps:
            - name: Clone repository
              uses: actions/checkout@v4
              with:
                  submodules: false
                  persist-credentials: false

            - name: Set up Deno
              uses: denoland/setup-deno@v2

            - name: Format
              run: deno fmt --check

            - name: Lint
              run: deno task lint

            - name: Build for NPM
              run: deno task build

            - name: Publish (dry run)
              run: deno publish --allow-dirty --dry-run

            - name: Set up Node
              uses: actions/setup-node@v4
              with:
                  node-version: '22.x'
                  registry-url: 'https://registry.npmjs.org'

            - name: NPM (dry run)
              run: npm publish --dry-run
