name: publish

on:
    push:
        branches: [main]

jobs:
    publish:
        runs-on: ubuntu-22.04
        timeout-minutes: 30

        permissions:
            contents: read
            id-token: write

        steps:
            - name: Clone repository
              uses: actions/checkout@v4

            - name: Set up Deno
              uses: denoland/setup-deno@v2

            - name: Format
              run: deno fmt

            - name: Type check
              run: deno task test

            - name: Build for NPM
              run: deno task build

            - name: Publish (real)
              run: deno publish --allow-dirty

            - name: NPM (real)
              id: publish
              uses: JS-DevTools/npm-publish@v3
              with:
                  token: ${{secrets.NPM_TOKEN}}
                  access: public
                  provenance: true

            - name: Release on GitHub
              if: ${{ steps.publish.outputs.type }}
              uses: softprops/action-gh-release@v1
              with:
                  tag_name: v${{ steps.publish.outputs.version }}
                  draft: false
                  generate_release_notes: true
